// Command apiref generates the human-readable gt2 API reference from the
// canonical editor contract.
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strconv"
)

func main() {
	sourcePath := flag.String("source", "pluginapi.go", "canonical API source")
	outputPath := flag.String("output", "API_REFERENCE.md", "generated reference")
	supportOutputPath := flag.String("support-output", "", "optional generated client support data")
	flag.Parse()

	source, err := os.ReadFile(*sourcePath)
	if err != nil {
		fail(err)
	}
	fileSet := token.NewFileSet()
	file, err := parser.ParseFile(fileSet, *sourcePath, source, parser.ParseComments)
	if err != nil {
		fail(err)
	}
	file.Decls = publicDeclarations(file.Decls)

	var contract bytes.Buffer
	if err := format.Node(&contract, fileSet, file); err != nil {
		fail(err)
	}
	sum := sha256.Sum256(source)
	var reference bytes.Buffer
	fmt.Fprintln(&reference, "# gt2 Scripting API 2 Reference")
	fmt.Fprintln(&reference)
	fmt.Fprintln(&reference, "Generated from `pluginapi.go`; do not edit this file directly.")
	fmt.Fprintf(&reference, "Source SHA-256: `%x`\n\n", sum)
	fmt.Fprintln(&reference, "Import the API with `import \"gt2\"`.")
	fmt.Fprintln(&reference)
	fmt.Fprintln(&reference, "```go")
	reference.Write(contract.Bytes())
	fmt.Fprintln(&reference, "```")

	if err := os.WriteFile(*outputPath, reference.Bytes(), 0o644); err != nil {
		fail(err)
	}
	if *supportOutputPath != "" {
		module, err := os.ReadFile("go.mod")
		if err != nil {
			fail(err)
		}
		writeSupportData(*supportOutputPath, module, source, reference.Bytes())
	}
}

func writeSupportData(outputPath string, module, contract, reference []byte) {
	var generated bytes.Buffer
	fmt.Fprintln(&generated, "// Code generated by gt2/cmd/apiref; DO NOT EDIT.")
	fmt.Fprintln(&generated, "package main")
	fmt.Fprintln(&generated)
	fmt.Fprintln(&generated, "var embeddedGT2EditorFiles = []struct {")
	fmt.Fprintln(&generated, "\tpath string")
	fmt.Fprintln(&generated, "\tdata []byte")
	fmt.Fprintln(&generated, "}{")
	for _, file := range []struct {
		path string
		data []byte
	}{
		{path: "gt2/go.mod", data: module},
		{path: "gt2/pluginapi.go", data: contract},
		{path: "gt2/API_REFERENCE.md", data: reference},
	} {
		fmt.Fprintf(&generated, "\t{path: %s, data: []byte(%s)},\n", strconv.Quote(file.path), strconv.Quote(string(file.data)))
	}
	fmt.Fprintln(&generated, "}")
	formatted, err := format.Source(generated.Bytes())
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		fail(err)
	}
}

func publicDeclarations(declarations []ast.Decl) []ast.Decl {
	public := make([]ast.Decl, 0, len(declarations))
	for _, declaration := range declarations {
		switch declaration := declaration.(type) {
		case *ast.FuncDecl:
			if ast.IsExported(declaration.Name.Name) {
				declaration.Body = nil
				public = append(public, declaration)
			}
		case *ast.GenDecl:
			if declaration.Tok == token.IMPORT {
				public = append(public, declaration)
				continue
			}
			specs := declaration.Specs[:0]
			for _, specification := range declaration.Specs {
				if isPublicSpecification(specification) {
					specs = append(specs, specification)
				}
			}
			if len(specs) > 0 {
				declaration.Specs = specs
				public = append(public, declaration)
			}
		}
	}
	return public
}

func isPublicSpecification(specification ast.Spec) bool {
	switch specification := specification.(type) {
	case *ast.TypeSpec:
		return ast.IsExported(specification.Name.Name)
	case *ast.ValueSpec:
		for _, name := range specification.Names {
			if ast.IsExported(name.Name) {
				return true
			}
		}
	}
	return false
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "generate gt2 API reference:", err)
	os.Exit(1)
}
