package main

import (
	"encoding/hex"
	"testing"
)

func TestAnswerChallengeLegacy(t *testing.T) {
	challenge := []byte{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15}
	// Expected value generated by the legacy client for password "demo" and
	// a challenge consisting of the bytes 0x00..0x0f.
	want, _ := hex.DecodeString("83cb8194932e8954358b32719f7ab80b")
	got, err := answerChallenge("demo", challenge)
	if err != nil {
		t.Fatalf("answerChallenge failed: %v", err)
	}
	if hex.EncodeToString(got) != hex.EncodeToString(want) {
		t.Fatalf("unexpected answer: got %x want %x", got, want)
	}
}
